### ISSUE TITLE
Custom job names don't appear to make it into the request / job-specific names should be created by default

### ISSUE THREAD

**Issue by nickwg03** [NREL/reV#105]
**Bug Description**
I'm trying to submit a new aggregation job, but it appears that since I already have a separate aggregation job running, reV thinks the new job I'm submitting is already running even though they are unrelated.

When I try to change the job name, it doesn't appear to fix the issue so that both aggregation jobs can run at the same time.

I think this is likely what is causing the batch to only run one job at a time, as well, since it is thinking a job is already running when it should in fact be running multiple jobs in prallel.

**Full Traceback**
```
[ngrue@el1 lopez_wind]$ reV -c "config_pipeline_reduced_binclass.json" -n lopez_wind_agg2 pipeline
INFO - 2020-01-29 10:00:54,224 [pipeline.py:127] : reV pipeline submitting: "aggregation" for job "outputs"
[ngrue@el1 lopez_wind]$ reV -c "config_pipeline_reduced_binclass.json" -n lopez_wind aggregation^C
[ngrue@el1 lopez_wind]$ reV -c "config_aggregation_reduced_binclass.json" -n "lopez_wind" aggregation
/home/ngrue/reV/reV/utilities/execution.py:485: UserWarning: Not submitting job "outputs_agg" because it is already in squeue with status: "R"
  'squeue with status: "{}"'.format(name, status))
Was unable to kick off reV SC job "outputs_agg". Please see the stdout error messages
```

**Code Sample**

`reV -c "/projects/rev/new_projects/lopez_wind/config_aggregation_reduced_binclass.json" -n "lopez_wind" aggregation`

**To Reproduce**
this is the job already running that is confusing reV:
```
[ngrue@el1 ~]$ squeue -u ngrue
             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
           2348097  standard outputs_    ngrue  R   16:22:51      1 r6i3n30
```
**Expected behavior**
reV should be able to discern when previously running jobs are related or unrelated to the new request. Additionally, custom job names should make it into the sbatch request to allow for running if issues like this come up.

**Charge code**
WEPG.10348.08.01.03

**Comment by MRossol** [comment]
@grantbuster, can we close this?

**Comment by grantbuster** [comment]
Yes, I'm not sure its fully resolved but its clearly not a critical bug.
