### ISSUE TITLE
Batch to raise warning on output dir

### ISSUE THREAD

**Issue by grantbuster** [NREL/reV#107]
**Why this feature is necessary:**
Batch gets messed up when output dir is not ./ (and actually all reV modules work best when output dir is ./)

**A possible solution is:**
Have batch raise warning. Always raise warning in config. 

**Additional context**
There is a larger issue with job names and priorities for job names. Batch might also want to raise an error if job name is specified.

**Comment by MRossol** [comment]
@grantbuster , did we fix this, is it still needed? I ran PERFORM fine with output dir not being ./ but that wasn't a batch run...

**Comment by grantbuster** [comment]
no, we should still do this

**Comment by ppinchuk** [comment]
The option to specify an output directory (and/or a job name) was removed in #352
