### ISSUE TITLE
Add "sum" to options for layer characterization during aggregation

### ISSUE THREAD

**Issue by nickwg03** [NREL/reV#131]
**Why this feature is necessary:**
For layers like landscan that lists the count of people for each pixel, this would give us the ability to see the total count of people within a supply curve aggregation block.

**A possible solution is:**
adding a `np.sum` to the existing `mode` and `mean` options under `data_layers`

**I have considered the following alternatives:**
Apart from post-processing after running SC, `mode` and `mean`doesn't give us the ability to compute this.

**Charge code**
Typical WETO tasks.

**Urgency / Timeframe**
If at all possible in the next few days would be great for our ATB portfolio.
@grantbuster

**Comment by grantbuster** [comment]
https://github.com/NREL/reV/pull/132

**Comment by nickwg03** [comment]
Awesome, thanks so much!
