### ISSUE TITLE
Add total count characterization to all aggregation / supply curve results

### ISSUE THREAD

**Issue by nickwg03** [NREL/reV#138]
@grantbuster 
**Why this feature is necessary:**
When using the `sum` aggregation method, having a total count for each supply curve would give us a way to calculate percent inclusion for a given characterization layer.

**A possible solution is:**
Count the total number of included pixels in a SC point's extent regardless of the pixel's percent inclusion. Any pixel with 1% or greater inclusion would be included in the count.

**I have considered the following alternatives:**
Passing in a raster that is all 1's to produce the same count, but is less graceful.

**Additional context**

**Charge code**
WETO tasks.

**Urgency / Timeframe**
Today would be great so we can kick off the rest of the WETO runs.

**Comment by grantbuster** [comment]
@MRossol  is going to implement this now.

**Comment by MRossol** [comment]
added in #139
