### ISSUE TITLE
Refactor __init__ and reV_run in Econ, Gen, SAM, Economics, and Generation

### ISSUE THREAD

**Issue by MRossol** [NREL/reV#141]
There currently is no simple way to run the above classes to complete outside of the __init__.
Also for Econ and Gen, I don't love the initialization of the output file in the __init__

See the refactor of the Offshore class for a good example
https://github.com/NREL/reV/pull/126

**Comment by MRossol** [comment]
@grantbuster  I'll take a go at this as it will give me the chance to learn those Modules

**Comment by grantbuster** [comment]
@MRossol can you wait until we close Mike's pull request?

**Comment by MRossol** [comment]
@grantbuster and @mikebannis  no problem. I also want to wait until I close my branch

**Comment by MRossol** [comment]
Cleaned up in prior refactor
