### ISSUE TITLE
Allow cases where there are more SC points than CF profiles in representative-profiles.

### ISSUE THREAD

**Issue by WilliamsTravis** [NREL/reV#160]
**Why this feature is necessary:**

There are cases when an aggregation might result in more supply curve points than generation points. This is handled well through supply-curve, but breaks on representative profiles. If it was possible to choose representative profiles even in this case it would be useful. 

**A possible solution is:**
This was apparently possible in reV version 1.

**Comment by nickwg03** [comment]
Raising this one again because I hit it today. Received the error below:
```
reV.utilities.exceptions.FileInputError: reV SC summary table has 8806 sc points and CF dataset "cf_profile-2014" has 2894 profiles. There should never be more SC points than CF profiles.
```

I think it's fine to have more SC points that CF profiles in cases where the agg factor is low (16 or 32) and would give a lot of SC points.

**Comment by MRossol** [comment]
@nickwg03  Do you want us to just turn the raise into a warning? Or do we need to do some testing, dev of any sort?

**Comment by nickwg03** [comment]
No, I think just changing to a warning would be perfect.

**Comment by MRossol** [comment]
can you give me the full traceback. I need the file and line number

**Comment by MRossol** [comment]
nevermind, fixing now

**Comment by MRossol** [comment]
Okay pushed to master, updating env right now. On @nickwg03  if this breaks reV left and right ;-)
