### ISSUE TITLE
Add new columns to supply curve outputs

### ISSUE THREAD

**Issue by nickwg03** [NREL/reV#167]
**Why this feature is necessary:**
Some columns that exist in the ORCA input spreadsheet should be carried through to the output supply curve CSV.
Columns include: 

1. array_cable_CAPEX
2. export_cable_CAPEX
3. (this would need to be computed) array_cable_CAPEX + export_cable_CAPEX + trans_cap_cost (and can be named combined_cap_cost)

**A possible solution is:**
Automated: join the ORCA `sc_point_gid` to the wfarm_id column in the input ORCA spreadsheet (wfarm_id + 1e7) and migrate the additional columns over and do the computation for the combined_cap_cost

**I have considered the following alternatives:**
Manually: doing the join manually after the supply curve run is complete. This is a short-term fix but we'd need the columns above for any ReEDS runs going forward.

**Charge code**
WEPG.10348.08.01.01

**Urgency / Timeframe**
If at all possible, having these upgrades by COB Friday May 29th would allow us to incorporate the changes for new runs happening the week of June 1st -- otherwise we will do the column migration manually.

**Comment by MRossol** [comment]
@nickwg03 We don't have a general reV features task number (just a bug fix task number), can you and Galen figure out what we should bill this to?

**Comment by nickwg03** [comment]
@MRossol updated with charge code

**Comment by grantbuster** [comment]
@nickwg03, we got the feature built into a branch. Going to do the PR soon and merge to master by tomorrow. While we're reviewing, can you take a look at the example offshore SC output table and make sure its what you want:

https://github.com/NREL/reV/blob/gb/more_orca_cols/tests/data/offshore/ri_offshore_sc_baseline.csv

**Comment by nickwg03** [comment]
@grantbuster that looks right.

**Comment by grantbuster** [comment]
#171
