### ISSUE TITLE
Supply-Curve-Aggretion Min/Max method

### ISSUE THREAD

**Issue by WilliamsTravis** [NREL/reV#170]
**Why this feature is necessary:**
We were asked if we could add minimum and maximum wind speeds within each wind farm from the aggregation module. It might be useful for future requests data sets as well. 

**I have considered the following alternatives:**
We considered a post-processing strategy with the 'category' method, but that would probably blow up the output tables and if this was simple to add in that would be much preferable.

**Comment by MRossol** [comment]
@WilliamsTravis  Do you have an ETA for this as well as a task number?

**Comment by nickwg03** [comment]
@MRossol just bumping this one.

Not urgent, but would be nice to have rolled out with the next major change....? TN:
OOSP.10291.12.01.01

**Comment by grantbuster** [comment]
So add min/max here: https://github.com/NREL/reV/blob/ada540f05f7691dbcea46f155229eb1d9c2e1663/reV/supply_curve/point_summary.py#L472-L481

And maybe have methods be a list for multiple data layer "methods"

**Comment by grantbuster** [comment]
@nickwg03: closed in #199
