### ISSUE TITLE
Percent inclusions should just use the minimum inclusion

### ISSUE THREAD

**Issue by nickwg03** [NREL/reV#172]
**Bug Description**
With overlapping percent inclusions, we don't want to multiply a single pixel repeatedly with progressively smaller available area. For all overlapping percent inclusions, we just want the minimum inclusion. For example, with four overlapping layers of 0.25, 0.50, 0.75, and 1.00 inclusion, we'd just want to use the 0.25 inclusion for that pixel.

**Charge code**
**WCRD.11447.01.01.01**

**Comment by MRossol** [comment]
Implemented in #173
