### ISSUE TITLE
Representative profiles gid_counts don't match

### ISSUE THREAD

**Issue by nickwg03** [NREL/reV#175]
**Bug Description**
This appears to be a new bug introduced recently when running representative profiles. Pipeline will run up to representative profiles and then fail with the following error:

```
reV.utilities.exceptions.DataShapeError: Weights column "gid_counts" resulted in 2 weight scalars which doesnt match
 gid column "gen_gids" which yields profiles with shape (17520, 184).
```

**Full Traceback**
```
Traceback (most recent call last):
  File "/shared-projects/rev/modulefiles/conda_env/lib/python3.7/concurrent/futures/process.py", line 239, in _proce
ss_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/shared-projects/rev/modulefiles/gitrepos/reV/reV/rep_profiles/rep_profiles.py", line 515, in get_region_rep
_profile
    return r.rep_profiles, r.i_reps, r.rep_gen_gids, r.rep_res_gids
  File "/shared-projects/rev/modulefiles/gitrepos/reV/reV/rep_profiles/rep_profiles.py", line 431, in rep_profiles
    self._run_rep_methods()
  File "/shared-projects/rev/modulefiles/gitrepos/reV/reV/rep_profiles/rep_profiles.py", line 420, in _run_rep_metho
ds
    raise DataShapeError(e)
reV.utilities.exceptions.DataShapeError: Weights column "gid_counts" resulted in 2 weight scalars which doesnt match
 gid column "gen_gids" which yields profiles with shape (17520, 184).
```

**Code Sample**
Travis ran the representative profile module with an older version of reV, so the profiles in the directory below are from that run. Previous runs with the current version of reV failed before writing out the profile HDFs. To reproduce the error:
1. use the shared modulefiles to run reV
2. run representative profiles (using the pipeline config) in this directory: `/shared-projects/rev/projects/duke/rev/solar/aggregation`

**Charge code**
WCRD.11447.01.01.01

**Comment by grantbuster** [comment]
I think rep profiles isnt handling a single SC point region very well. reeds_ba = 99 only has one valid SC point. I'll look into this more today.

**Comment by nickwg03** [comment]
@grantbuster that could be. This run excludes everything except North and South Carolina, which includes only BA's: 95, 96, 97, 98, 99.

**Comment by grantbuster** [comment]
@nickwg03, I think we found the bug. It's unrelated to your SC output table. Fixing now.

**Comment by grantbuster** [comment]
@nickwg03, it was actually in rex. The module files are updated as are the reV/rex versions and dependencies. I've rerun your rep profiles project with outputs here: /lustre/eaglefs/shared-projects/rev/projects/duke/rev/solar/aggregation
