### ISSUE TITLE
reg_cols during representative profiles module will unknowingly skip columns requested that don't exist in SC results

### ISSUE THREAD

**Issue by nickwg03** [NREL/reV#176]
**Bug Description**
When running the representative profiles module, if a column is specified in `reg_cols` that doesn't exist in the SC CSV file, the rep profile module will skip it without warning and just aggregate whatever columns do exist. For example, I specified `reeds_ba` and `res_class` in `reg_cols`, but only `res_class` existed (`reeds_ba` did not) so the rep profile module aggregated something, but I don't really know what.

project directory is `/projects/rev/new_projects/reeds_wind/duke/orig_run`

**Full Traceback**
There may have been a subtle message in the rep profile log, but certainly not enough to raise attention.

**To Reproduce**
Steps to reproduce the problem behavior
cd to project directory above and run rep_profile with only `reeds_ba` and `res_class` specified in the `reg_cols`

**Expected behavior**
reV should break to allow the user to fix the `reg_cols` inputs.

**Charge code**
WCRD.11447.01.01.01

**Comment by MRossol** [comment]
Bad config, we really need to implement #161
