### ISSUE TITLE
test_gen_linear fails with PySAM v2

### ISSUE THREAD

**Issue by MRossol** [NREL/reV#178]
**Bug Description**
test_gen_linear.py is no longer passing, the comment suggests this is a PySAM version issue.

**Full Traceback**
https://github.com/nrel/reV/actions?query=workflow%3APytests

**Charge code**
WCRD 11447 01.01.01 unless you can charge this to the original feature task

**Comment by mikebannis** [comment]
Variation in output data appears to be caused by changes in pysam. While most output variables changed, 90% of the time series values were identical. For the time steps that changed, the relative MAE was 0.004% or better. Baseline values for tests have been updated.
