### ISSUE TITLE
Pipeline Broken

### ISSUE THREAD

**Issue by WilliamsTravis** [NREL/reV#190]
**Bug Description**
The pipeline must be resubmitted after every successful completion of a reV module. I'm fairly certain that this is because the project status json is not updating correctly. 

For each job id, "job_status" will remain as "submitted" until the pipeline is resubmitted even if its individual "jobstatus_*.json" file shows that it was successful. 

When resubmitting the pipeline following a successful module run, all statuses are immediately updated to "successful". 

**To Reproduce**
1. Go to '/shared-projects/rev/projects/soco/rev/runs/reference/generation/160hh/20ps'
2. Copy configs somewhere.
3. Run "reV -c config_pipeline.json pipeline"
4. Wait for your SLURM queue to clear and check outputs and logs.

**Expected behavior**
With one pipeline command, reV runs and completes the generation module, then pipes the results into the collect module, then pipes those results into the multi-year file, only stopping if there was an error.

**System**
 - OS: Linux
 - Compute hardware: Eagle
 - Version 0.4.10 & 0.4.4

**Additional context**
This seems to have progressed over time. With previous versions, I remember having some trouble with it for a while, but also having it work most of the time. Now this behavior is very consistent.

**Charge code**
This is somewhat urgent, we are getting ready to run a fairly large number of configuration permutations for a project and it would be very difficult to submit every module for each one. 

WCRD.11029.01.01.01

**Comment by grantbuster** [comment]
Use `--monitor`
