### ISSUE TITLE
Supply-Curve Fails

### ISSUE THREAD

**Issue by WilliamsTravis** [NREL/reV#196]
**Bug Description**
The supply curve module is failing with the message below. It works on reV version 0.3.1.

"Error: No such command '2'.

**Full Traceback**
Usage: cli_supply_curve.py direct [OPTIONS] COMMAND [ARGS]...

Try 'cli_supply_curve.py direct --help' for help.

Error: No such command '2'.

**To Reproduce**
Steps to reproduce the problem behavior
1. Run the supply-curve module on Eagle.

**Expected behavior**
Runs and outputs a supply-curve csv.

**Screenshots**

**System (please complete the following information):**
 - OS: Linux
 - Compute hardware: Eagle
 - Version: 0.4.12 & 0.4.14

**Comment by grantbuster** [comment]
@WilliamsTravis can you run with debug logging and provide the log file?

**Comment by WilliamsTravis** [comment]
@grantbuster 
(/home/twillia2/.conda-envs/revruns) [twillia2@ed3 logs]$ cat test_sc.log 
INFO - 2020-08-18 09:54:24,720 [cli_supply_curve.py:74] : Running reV supply curve from config file: "/lustre/eaglefs/shared-projects/rev/projects/soco/rev/runs/reference/aggregation/120hh/120hh_150ps/test/config_supply-curve.json"
INFO - 2020-08-18 09:54:24,721 [cli_supply_curve.py:75] : Target output directory: "/lustre/eaglefs/shared-projects/rev/projects/soco/rev/runs/reference/aggregation/120hh/120hh_150ps/test/"
INFO - 2020-08-18 09:54:24,721 [cli_supply_curve.py:76] : Target logging directory: "./logs/"
DEBUG - 2020-08-18 09:54:24,721 [cli_supply_curve.py:78] : The full configuration input is as follows:
SupplyCurveConfig
INFO - 2020-08-18 09:54:24,722 [supply_curve_configs.py:237] : Supply curve using the following pipeline input for sc_points: /lustre/eaglefs/shared-projects/rev/projects/soco/rev/runs/reference/aggregation/120hh/120hh_150ps/test/test_agg.csv
INFO - 2020-08-18 09:54:24,949 [cli_supply_curve.py:376] : Running reV Supply Curve on SLURM with node name "test_sc"
DEBUG - 2020-08-18 09:54:24,949 [cli_supply_curve.py:377] : 	python -m reV.supply_curve.cli_supply_curve -n 'test_sc' direct -sc '/lustre/eaglefs/shared-projects/rev/projects/soco/rev/runs/reference/aggregation/120hh/120hh_150ps/test/test_agg.csv' -tt '/projects/rev/data/transmission/land_offshore_allconns_064.csv' -fcr 0.072 -scf '/projects/rev/data/transmission/conus_064_tline_multipliers.csv' -tc "{'line_cost': 3889, 'line_tie_in_cost': 96000, 'station_tie_in_cost': 0, 'available_capacity': 1, 'center_tie_in_cost': 0, 'sink_tie_in_cost': 0}" -so 'total_lcoe' -ott None-dirs 2 -mw None -o '/lustre/eaglefs/shared-projects/rev/projects/soco/rev/runs/reference/aggregation/120hh/120hh_150ps/test/' -ld './logs/' -v 
DEBUG - 2020-08-18 09:54:24,969 [execution.py:58] : The shell script "test_sc.sh" contains the following:
~~~~~~~~~~ test_sc.sh ~~~~~~~~~~
#!/bin/bash
#SBATCH --account=setallwind  # allocation account
#SBATCH --time=01:00:00  # walltime
#SBATCH --job-name=test_sc  # job name
#SBATCH --nodes=1  # number of nodes
#SBATCH --output=./logs/stdout//test_sc_%j.o
#SBATCH --error=./logs/stdout//test_sc_%j.e
#SBATCH --mem=90000  # node RAM in MB
#SBATCH --qos=normal  # extra feature
echo Running on: $HOSTNAME, Machine Type: $MACHTYPE

python -m reV.supply_curve.cli_supply_curve -n 'test_sc' direct -sc '/lustre/eaglefs/shared-projects/rev/projects/soco/rev/runs/reference/aggregation/120hh/120hh_150ps/test/test_agg.csv' -tt '/projects/rev/data/transmission/land_offshore_allconns_064.csv' -fcr 0.072 -scf '/projects/rev/data/transmission/conus_064_tline_multipliers.csv' -tc "{'line_cost': 3889, 'line_tie_in_cost': 96000, 'station_tie_in_cost': 0, 'available_capacity': 1, 'center_tie_in_cost': 0, 'sink_tie_in_cost': 0}" -so 'total_lcoe' -ott None-dirs 2 -mw None -o '/lustre/eaglefs/shared-projects/rev/projects/soco/rev/runs/reference/aggregation/120hh/120hh_150ps/test/' -ld './logs/' -v 
~~~~~~~~~~ test_sc.sh ~~~~~~~~~~
DEBUG - 2020-08-18 09:54:24,994 [execution.py:751] : SLURM job "test_sc" with id #Submitted batch job 4017547 submitted successfully
INFO - 2020-08-18 09:54:25,001 [cli_supply_curve.py:393] : Kicked off reV SC job "test_sc" (SLURM jobid #4017547).

**Comment by MRossol** [comment]
fixed, missing a space here:
```
-ott None-dirs 2
```

**Comment by WilliamsTravis** [comment]
Thanks!
