### ISSUE TITLE
Exclusion layer flexibility

### ISSUE THREAD

**Issue by nickwg03** [NREL/reV#200]
**Bug Description**
Add ability to create more flexible exclusion layer arguments.

Allow for stand-in layer names that reference a dset name, and allow for applying different exclusion weights (see code below for example).
![3f2b8b3d-e72c-4c1e-bbe3-9b30c4e76498](https://user-images.githubusercontent.com/4528512/91902762-6f34c900-ec5f-11ea-9a74-b2ec5260727d.jpg)

**Charge code**
OOSP.10291.12.01.01

**Comment by nickwg03** [comment]
Oops, meant to make a feature not a bug.

**Comment by grantbuster** [comment]
It's a feature not a bug! haha. 

Probably should implement here: https://github.com/NREL/reV/blob/ada540f05f7691dbcea46f155229eb1d9c2e1663/reV/supply_curve/exclusions.py#L766-L769

**Comment by MRossol** [comment]
@nickwg03  implemented in #201 updating Eagle Module now and will release with v0.4.16

See example config here: 
https://github.com/NREL/reV/blob/97043c8530b2516a45e6745d4912c3f7462dd24e/examples/full_pipeline_execution/config_aggregation.json#L17-L24
