### ISSUE TITLE
Multiple collect steps in pipeline

### ISSUE THREAD

**Issue by grantbuster** [NREL/reV#21]
Currently the pipeline status is keyed by cli command, which assumes each module is only run once. collect might be have to run twice.

**Comment by grantbuster** [comment]
Don't have an immediate need for this since we added the append feature to the Econ module.

**Comment by ppinchuk** [comment]
After #415 is merged, this functionality will be on [GAPs](https://github.com/NREL/gaps) to implement, so we may wish to move this issue there.

Ok to close this @grantbuster?

**Comment by grantbuster** [comment]
yeah sounds good, please open a similar issue on gaps. This would still be good functionality to add at some point.
