### ISSUE TITLE
Pipeline to pass gen_fpath through aggregation for rep_profiles access 

### ISSUE THREAD

**Issue by grantbuster** [NREL/reV#212]
**Why this feature is necessary:**
If you want to run a generation project then an SC agg / rep_profiles project separately, you need the rep_profiles config to be able to see the gen_fpath in the status json. 

**A possible solution is:**
SC agg can pass the gen_fpath [here](https://github.com/NREL/reV/blob/f5b8a7aac6d478a6ecadf03b1018d6a46efe091a/reV/supply_curve/cli_sc_aggregation.py#L312) which rep_profiles needs to be able to pick up [here](https://github.com/NREL/reV/blob/f5b8a7aac6d478a6ecadf03b1018d6a46efe091a/reV/config/rep_profiles_config.py#L46-L54)

**Charge code**
Ask Nick Grue

**Urgency / Timeframe**
Medium urgency, ask Nick Grue.

**Comment by nickwg03** [comment]
Lol, who am I, moneybags? If this gets done before April 2021, use: `WFED.11785.01.01.01`
If after that, then ask me.

**Comment by MRossol** [comment]
Sweet so I have until April 2021 to fix this, love it!

**Comment by grantbuster** [comment]
implemented here: https://github.com/NREL/reV/tree/gb/agg_lcoe

**Comment by MRossol** [comment]
Implemented in #318
