### ISSUE TITLE
Refactor reV generation project points parsing

### ISSUE THREAD

**Issue by grantbuster** [NREL/reV#217]
**Why this feature is necessary:**
The reV generation method `_pp_to_pc()` is a total nightmare mess. I think we've patched this for super specific econ cases and it breaks some more simple generation use cases. Specifically this chunk of code can overwrite a smaller set of points with a larger set. I think we should try to greatly simplify this code and implement the special cases in econ.

https://github.com/NREL/reV/blob/38d61923d15879ef8f2011d4ad7434797b7ac842/reV/generation/generation.py#L907-L926

**Workaround**
Run reV from config (project points as csv works fine) or input PointsControl to reV generation explicitly. 

**Charge code**
unknown 

**Urgency / Timeframe**
Medium.

**Comment by MRossol** [comment]
Move If section to Econ

**Comment by grantbuster** [comment]
@MRossol closing this as i think you implemented in #218
