### ISSUE TITLE
Formalize dumping out DC outputs to reV generation HDFs

### ISSUE THREAD

**Issue by nickwg03** [NREL/reV#223]
**Why this feature is necessary:**
Having the DC output profiles provides greater flexibility to downstream capacity expansion models.

**A possible solution is:**
dump out the DC outputs, but provide proper integer scaling and units.

**Charge code**
GMLC.10246.09.05.01

**Urgency / Timeframe**
Deliverable end of the quarter, but we'd need a few weeks beforehand to run reV and ensure our outputs are correct.

**Comment by grantbuster** [comment]
@nickwg03 what kind of integer scaling do you want for this? I'm not sure this is a good idea because there's not a fixed upper bound to the DC or AC power generation. I can add it to the list of known outputs as float32 in units of kW.

**Comment by MRossol** [comment]
I'm with Grant, I think fixing the dtype to float32 is more robust than trying to force a scale-factor. We've run into this recently with some new WRF variables that have indeterminate upper-bounds.

**Comment by grantbuster** [comment]
Implemented in #226

**Comment by nickwg03** [comment]
Yep, that's fine. I was just paraphrasing from a conversation on Teams from a few weeks back. Units/scaling doesn't matter to me.
