### ISSUE TITLE
Output voltage at each timestep from SAM

### ISSUE THREAD

**Issue by nickwg03** [NREL/reV#224]
**Why this feature is necessary:**
I'm not sure if it's available from SAM, but the voltage outputs for each time step would be useful for downstream CEM modelers.

**Charge code**
GMLC.10246.09.05.01

**Urgency / Timeframe**
Not as high priority as https://github.com/NREL/reV/issues/223 but having this within the next month or two would be most beneficial.

**Comment by grantbuster** [comment]
I dont think voltage is an available output from PVWatts. I'm closing this unless you have some fancy way you want us to calculate it.
