### ISSUE TITLE
Change stringified dict to actual dict when creating batch scenarios based on CSV input

### ISSUE THREAD

**Issue by nickwg03** [NREL/reV#231]
**Why this feature is necessary:**
Being able to vary the individual layer arguments within the `excl_dict` would make doing scenario'd runs much easier when we build numerous scenarios that only change arguments within the `excl_dict`. Right now, the process creates a stringified dictionary instead of an actual dictionary. Forcing the dictionary would make the resulting batch JSON usable.

**A possible solution is:**
Force stringified dict into an actual dict

**Additional context**
Below are screenshots of the input batch CSV config, and the batch JSON config with stringified dict.

![df372a1e-c099-4d34-9899-e9e68399f86c](https://user-images.githubusercontent.com/4528512/98294213-cc553f80-1f6c-11eb-9513-2e7bbad015b1.jpg)
![imgo](https://user-images.githubusercontent.com/4528512/98294225-d24b2080-1f6c-11eb-8ab0-2fc4ca4ab276.jpg)

**Charge code**
WFED.10406.19.01.01

**Urgency / Timeframe**
Would need ready to go by Fri, Nov 20th. Earlier is always appreciated :)

**Comment by MRossol** [comment]
implemented in #232
