### ISSUE TITLE
Add distributed for representative profiles

### ISSUE THREAD

**Issue by nickwg03** [NREL/reV#242]
**Why this feature is necessary:**
I'm running with a new set of solar exclusion scenarios and a reduced resolution (32, compared to 64 in previous runs), and for the least restrictive (most points) I have about 800k points that need to be aggregated into representative profiles.

After an hour of running, these runs were only about 10% done -- meaning I'd need probably 8-12 hours to be able to run rep profiles for these points each time.

**A possible solution is:**
Allow for multiple nodes to churn through these points instead of limiting to one node.

**I have considered the following alternatives:**
Just waiting. But, you know...

**Additional context**
This volume of SC points for solar will likely persist for future projects, so making this upgrade now will be a big help for future projects.

**Charge code**
Can you provide an estimate on time? At that point I'll provide which charge code to use.

**Urgency / Timeframe**
I can manage for the time being, but this would be helpful sooner than later.

**Comment by grantbuster** [comment]
I think this might be kind of involved. Maybe 40 to 60 hours and could take 2 weeks. 

Questions:
- what kind of aggregation are you doing? 
- is this using the aggregate_profiles flag to get the mean profile? 
- or are you using the baseline rep profile method that finds the closest-to-meanoid? 
- Also what kind of regions are you aggregating across? 
- Is it for REEDS regions, states, ISO's? 
- How many regions are you targeting? How many output profiles are you requesting assuming 1 profile per region?

**Comment by MRossol** [comment]
@nickwg03  I'm with Grant, I don't think this is as straight forward as you are suggesting. If we were to distribute this across nodes we'd then have to re-collect the .h5 files after the fact. I think trying to improve performance on one node would be a better first step...

**Comment by nickwg03** [comment]
Thanks, let me think on that estimate as that's a lot of money for one project.
If you have alternative approaches that wouldn't need to use multiple nodes, let me know your estimates for those.

To answer your questions:
1. Resolution == 32, meaning 2880m X 2880m resolution.
2. I'm using `aggregate_profiles` -- this is pretty much what ReEDS wants now as they use Hourlize to aggregate to regions.
3. Not sure on the baseline rep profile, I'm not able to specify the method when using aggregate_profiles.
** I think the rest of the questions would be if we weren't using `aggregate_profiles` right?

**Comment by MRossol** [comment]
HOW THE F did our reV to ReEDS code get replaced by this:
https://github.com/mmowers/hourlize

**Comment by nickwg03** [comment]
Am I wrong about this? I thought we just ran `aggregate_profiles` every time and then hourlize could flexibly aggregate to regions.

**Comment by nickwg03** [comment]
Closing this one as there appear to be options already available.
