### ISSUE TITLE
Economies of Scale Wind CapEx multiplier

### ISSUE THREAD

**Issue by MRossol** [NREL/reV#247]
**Why this feature is necessary:**
Apply CapEx cost reductions due to economy of scale for Wind Farm development. This need to be applied to the aggregate wind profiles

**A possible solution is:**
Pipeline:
- Generation
- Aggregation
- Aggregate Profiles
- Econ on Aggregate wind profiles using CapEx multiplier curves from Owen
- Update Aggregation table LCOEs
- Supply Curve

**Charge code**
WEPG 10348 08.01.01

**Urgency / Timeframe**
Q2-Q3

**Comment by MRossol** [comment]
New plan:
Add economies of scale kwarg to gen and econ
- kwarg would add LCOE input values to output_requests
- Add a economies_of_scale.py to econ
- Add function or class to scale and recompute LCOE manually
- Add kwarg to pass in equation to aggregate_profiles, if valid run economies of scale

**Comment by MRossol** [comment]
SAM LCOE:
https://sam.nrel.gov/financial-models/lcoe-calculator.html

**Comment by MRossol** [comment]
[Uploading 2.4.3.407 MHKDR AOP FY21.docx…]()

**Comment by grantbuster** [comment]
Integrated into #253. The user needs to perform the following steps to run economies of scale:

1. add the lcoe inputs to the output request in gen/econ/collect. 
2. There's a new argument next to "dsets" in multi-year collection called "pass_through_dets", add the LCOE input variable names here.
3. input a "cap_cost_scale" in the supply curve aggregation step. This can be a string equation with independent variables from the aggregation table (e.g. "2 * capacity ** -0.5"). The output of this equation should be a scalar that is applied to the capital_cost.
