### ISSUE TITLE
Store representative profiles as int instead of float

### ISSUE THREAD

**Issue by nickwg03** [NREL/reV#250]
**Why this feature is necessary:**
Talking with Matt Mowers, the representative profiles are being stored as float, and it would probably be better data management to store as int like is done for the generation profiles. This will become more important with higher spatial/temporal resolutions especially when 20 years of wind becomes available.

**Charge code**
Would preferably cost share with ReEDS, so let's talk with Mowers about a combination of task numbers.

**Urgency / Timeframe**
Not urgent, but something that will probably be needed in the future.

**Comment by MRossol** [comment]
@nickwg03, do you have a task number for this? Its probably only a few hours of work, i'm honestly a bit surprised the rep_profiles aren't scaled as that is usually our default...

**Comment by WilliamsTravis** [comment]
This finally has a task number:
reV Maintenance GDOP.12495.31.01.01

**Comment by WilliamsTravis** [comment]
Issue addressed at some point without me noticing it. We're now able to store rep-profiles as ints with the `scaled_precision` option
