### ISSUE TITLE
No bin/$OS/ directory

### ISSUE THREAD

**Issue by rqurio** [NREL/reV#254]
**Bug Description**
No` bin/$OS/` directory

Trying to follow installation guidelines provided [here](https://nrel.github.io/reV/misc/installation.html#option-2-clone-repo-recommended-for-developers).

After clonning, step 2 mentions cd into ` bin/$OS/` directory. But there is no such directory.

If this module is pip installed on AWS EC2 (Ubuntu) instance, will it work?

**Comment by MRossol** [comment]
@rqurio please see updated documentation, but unless you are planning on developing reV I'd recommend using [installation option 1](https://nrel.github.io/reV/#option-1-install-from-pip-or-conda-recommended-for-analysts) to install from pip or conda on your EC2 instance. reV is compatible with Ubuntu, MacOSX, and Windows.

**Comment by rqurio** [comment]
@MRossol , in updated documentation under option #2, point 4 is missing.
________________________________

**Comment by MRossol** [comment]
whoops, no steps were missing the numbering was just messed up!
