### ISSUE TITLE
Add an option to wait between batch submissions.

### ISSUE THREAD

**Issue by WilliamsTravis** [NREL/reV#260]
**Why this feature is necessary:**
Eagle has implemented a new monitoring system that is more strict about login node cpu usage (Arbiter2). When submitting batch jobs python processes combine to exceed the threshold cpu usage for a short period until the submission process is complete, resulting in temporary cpu throttling for the offending user and an unpleasant email from HPC.

**A possible solution is:**
Add in an option to wait with a default of a minute or two between individual job submissions in the batch module. One minute is probably enough but two would likely ensure that the threshold isn't passed.

**Urgency / Timeframe**
This is only going to be a problem for large batch jobs and there are none in the next couple of months.

**Comment by ppinchuk** [comment]
@WilliamsTravis Is this still really an issue? I haven't ran into it at all.

Once easy workaround that seems a bit silly at first but is perfectly practical is to checkout a compute node to do your submissions from. Then you are not hitting the login nodes at all and can submit batch jobs without any delays.

In any case, after #415 is merged, this will be entirely on [GAPs](https://github.com/NREL/gaps) to implement, so feel free to open an issue there if it still comes up.
