### ISSUE TITLE
Supply-Curve-Aggreation: Take partial exclusions into account for data_layer characterization sums

### ISSUE THREAD

**Issue by WilliamsTravis** [NREL/reV#261]
**Bug Description**
In supply-curve-aggregation, the "sum" characterization method for data_layers appears to be adding the pixel counts within a supply curve point before removing partial exclusions. We would like this figure to allow us to calculate the area of non-excluded land within each characterization.

**Expected behavior**
The sum of a characterization layer is a float taking into account partial exclusions.

**System (please complete the following information):**
 - OS: Linux
 - Compute hardware Eagle
 - Version: v0.4.43

**Comment by MRossol** [comment]
@WilliamsTravis is this what you were envisioning:
https://github.com/NREL/reV/blob/77c77a065b6be7704eae09c13e1e964ddaa289e5/reV/supply_curve/point_summary.py#L472-L473
