### ISSUE TITLE
SC Aggregation Exclusions Optimization

### ISSUE THREAD

**Issue by grantbuster** [NREL/reV#267]
**Why this feature is necessary:**
There is a possibility for optimization of the supply curve aggregation algorithm regarding how we read/compute exclusions. Currently we distribute the read/compute of the aggregated exclusions to each supply curve point being worked on each worker. We previously thought that computing the full exclusion mask at once would be prohibitively slow. However, the `check_excl_layers` kwarg to the SC aggregation does exactly this and is pretty fast. I think it might be faster to do the full exclusion mask read/compute ahead of time, then distribute each SC point's portion of the exclusion mask to the respective workers. This refactor would be similar to how we read in the full generation / resource means and then distribute instead of doing the read on each individual worker. 

**Charge code**
Get from whoever is having the greatest difficulty with SC aggregation.

**Urgency / Timeframe**
Contingent on further SC aggregation performance issues.

**Comment by MRossol** [comment]
Fixes #283

**Comment by MRossol** [comment]
Implemented in #285
