### ISSUE TITLE
Build in flag to re-calc LCOE in multi-year mean and sc-agg modules

### ISSUE THREAD

**Issue by grantbuster** [NREL/reV#277]
**Why this feature is necessary:**
We should have an option to calculate LCOE using the lifetime average AEP. Should be a simple addition to the multiyear mean module and the sc-aggregation module. 

**Charge code**
WEPG.10348.08.01.01

**Urgency / Timeframe**
Medium

**Comment by grantbuster** [comment]
implemented here: https://github.com/NREL/reV/tree/gb/agg_lcoe

Currently a bit rough - will re-calc lcoe by default if the available datasets are in the `h5_dsets` input argument (system_capacity, fixed_charge_rate, capital_cost, fixed_operating_cost, and variable_operating_cost)

**Comment by grantbuster** [comment]
added warnings if the requisite re-calc datasets are either not found in h5_dsets or not found in the source file

**Comment by MRossol** [comment]
Implemented in #318
