### ISSUE TITLE
Offshore Supply Curve Point Region Assignment

### ISSUE THREAD

**Issue by alopez04** [NREL/reV#279]
**Bug Description**
For reV offshore, it looks like the supply curve points are assigned to a region based on the offshore cable landfall/interconnection. This creates differences in state capacity totals depending on the land-based siting regime - even though offshore capacity/exclusions remain constant. A more consistent approach would be to assign the region based on the supply curve point location using offshore region boundaries. 

**Charge code**
WEPG.10348.08.01.03

**Comment by MRossol** [comment]
@grantbuster, will this be fixed with the NRWAL integration? I think the actual issue was that offshore SC points were pre-defined by ORCA.

**Comment by grantbuster** [comment]
I'm not sure what the proposed solution is. The offshore supply curve points derived from NRWAL outputs will have the meta data attributes from the WTK. In anthony's comment: "assign the region based on the supply curve point location using offshore region boundaries", what offshore region boundaries are those? You can always create exclusion grids with meta data and have aggregation summarize that meta data for the offshore sc points.

**Comment by MRossol** [comment]
Again my understanding of the "bug" is that the ORCA points are pre-defined and thus don't get any data during aggregation. @alopez04, now that offshore points are aggregated like onshore points and we can apply layers to them can we call this "fixed".

**Comment by grantbuster** [comment]
Gotcha, yes we can apply aggregation "data layers" to the offshore supply curve points now (reeds regions or whatever else you cook up). However i should note that the WTK doesnt have country/state/county values for the offshore meta data so the offshore supply curve points will not automatically have meta data for these fields.

**Comment by MRossol** [comment]
Very good point, couldn't we add that in through NRWAL. It would be a bit hacky but we could add region data columns to the inputs and then pass them through

**Comment by grantbuster** [comment]
Yes I think youre right
