### ISSUE TITLE
Clean up Gen tests

### ISSUE THREAD

**Issue by MRossol** [NREL/reV#290]
**Bug Description**
@mikebannis  your Generation tests keep failing every time the PySAM version changes. Can you refactor them to be more robust. I'd suggest removing hard-coded "true" values and instead caching baseline results from PySAM 2.1.4 and then use np.allclose or pandas assert_frame_equals with a rtol and atol tolerance.

**Full Traceback**
https://github.com/NREL/reV/pull/289/checks?check_run_id=2271778550

**Code Sample**
See PV and wind tests:
https://github.com/NREL/reV/blob/main/tests/test_gen_wind.py
https://github.com/NREL/reV/blob/main/tests/test_gen_pv.py

**Expected behavior**
More deterministic test results with PySAM version changes

**Charge code**
WEPG 10348 08.01.01

**Comment by mikebannis** [comment]
That one has bit me already. I'm unsure on the difference between hard-coded and caching in the context above. Should the tests be generating PySAM 2.1.4 results on the fly or should they be saved in the repo?

**Comment by MRossol** [comment]
Save them in the repo:
https://github.com/NREL/reV/blob/719b3ed16c72bfed4eccde50507cf0dd89dae1db/tests/test_gen_pv.py#L88-L89

**Comment by MRossol** [comment]
@mikebannis Anything I can do here to close this out and merge the #289

**Comment by mikebannis** [comment]
@MRossol I haven't gotten to this yet. Do you have a timeline?

**Comment by MRossol** [comment]
I'll take a wack at it while you focus on Transmission costs
