### ISSUE TITLE
reV outputs handler doesnt have correct Resource attributes

### ISSUE THREAD

**Issue by grantbuster** [NREL/reV#300]
**Bug Description**
The reV outputs handler never calls resource init() and so doesnt get a lot of the correct attributes initialized. Can we call super().__init__()?

Here are some of the things we need, for example to run the Outputs.dtypes property:
https://github.com/NREL/rex/blob/291689263ac0d99e4779d5e3f7c84b8e7736cdec/rex/resource.py#L729-L739

**Comment by MRossol** [comment]
Implemented a new BaseResource class: https://github.com/NREL/reV/issues/300
We can now super().__init__() from BaseResource
