### ISSUE TITLE
modify job names using reV -n $name command

### ISSUE THREAD

**Issue by MRossol** [NREL/reV#319]
**Why this feature is necessary:**
It would be much simpler to add a prefix to using the -n option than going in and modifying the config.json with a custom name. This way you could use the existing logic but add the -n value at the beginning.

**A possible solution is:**
Unfortunatley the use of -n is not consistent accross reV CLIs, the current issue at hand is with batch where the name doesn't seem to be used at all...

**Additional context**
For PERFORM I want to rerun the pv_forecast batch jobs for all three ISOs, but the produce identical job names.

**Charge code**
 ARPA 10957 65.01.01

**Comment by grantbuster** [comment]
Going a different direction as per #352
