### ISSUE TITLE
LCOT for SC Points that exceed 1500MW

### ISSUE THREAD

**Issue by MRossol** [NREL/reV#336]
**Bug Description**
The current hack for handling SC Points that exceed 1500MW is flawed. We currently connect those points to 500kV xmission features without changing the trans cap cost. When the trans cap cost is normalized by sc point capacity this produced abnormally low LCOTs.

**Full Traceback**
See e-mail thread with Patrick Brown and Trieu

**Expected behavior**
The original solution devised by Owen is the "correct" approach and would work as follows:
For SC points that > max tie-line capacity, the tie-line cost needs to be scaled by an integer multiplier equal to the # of tie-lines needed for the desired capacity and the trans_cap_cost recomputed. 
The multiplier would be computed as follows: `multiplier =  capacity // tie-line capacity + 1`

Typically the tie-line capacity would be 1500MW, but we should make this work for cases in which we don't pass in all the LC xmission classes

If we really want to be exact about this we should also consider re-computing the connection costs, namely the transformer cost...

**Additional context**
We pitched the "correct" solution to ReEDS and they suggested the hack (face palm emoji)

**Charge code**
ReV

**Comment by grantbuster** [comment]
okay, path forward: do what michael suggested with the Nx transmission lines for SC points that exceed the max capacity, but then also when running reV for ReEDS maybe only feed in least cost transmission tables up to the 400MW max capacity lines so that it mimics Nx 400MW solar plants connected in parallel instead of single 4GW solar plants which are exceptional.

**Comment by grantbuster** [comment]
An interesting effect of this is that an SC point could be connected to transmission via small capacity parallel lines even if a larger capacity line is available if the small parallel lines are more cost effective. Is this realistic? Seems reasonable?

**Comment by grantbuster** [comment]
okay, seems reasonable.

**Comment by grantbuster** [comment]
fixed in commit 4b83f1cef950b2ac55fe0c3c461a5ec86dffb8e6 and PR #370
