### ISSUE TITLE
NREL-PySAM v3.0.0 incompatible with reV

### ISSUE THREAD

**Issue by grantbuster** [NREL/reV#341]
**Bug Description**
Lots of bugs, see pytest logs here: https://github.com/NREL/reV/runs/4742528063?check_suite_focus=true

**To Reproduce**
1. Install reV and then nrel-pysam=3.0.0
2. Run pytests
3. Check errors for example on single owner execution

**Charge code**
Not sure

**Comment by ppinchuk** [comment]
Working on this as part of reV geothermal + an Exxon mobile project

**Comment by ppinchuk** [comment]
P.S. Sounds like we will have to upgrade to PySAM 4 "soon" for the Exxon Mobil project...
