### ISSUE TITLE
POI lon, lat in suppl curve table

### ISSUE THREAD

**Issue by alopez04** [NREL/reV#374]
**Why this feature is necessary:**
We'd like to add the latitude and longitude of the point of interconnection for wind (LBW & OSW) and solar supply curve points. Here's the scenario, a reV supply curve point is in offshore waters and is assigned a county in New Jersey, but the supply curve point has a point of interconnection in New York City. It matters a lot more for downstream modeling where the energy is going, not where the farm sits relative to state/county borders. Same is true for LBW and solar.  

**A possible solution is:**
Additional two columns in the resulting supply curve table that specify the latitude and longitude of the POI used. 

**I have considered the following alternatives:**
None. This is the correct approach ;)

**Additional context**
![image](https://user-images.githubusercontent.com/9019826/172263574-9f0ca44b-573f-480f-98c7-c1ca198cb729.png)

**Charge code**
WEPG.10348.08.01.06

**Urgency / Timeframe**
Not urgent / July 2022

**Comment by ppinchuk** [comment]
As of #396, reV will pass through the `poi_lat` and `poi_lon` columns, if they are already given in the transmission tables. Legacy transmission tables will not have those columns, but any transmission tables created [after this reVX update](https://github.com/NREL/reVX/pull/172) should have those columns (including the reinforcement costs tables). I think with that, we can close this issue, unless you have any other thoughts on this @grantbuster

**Comment by grantbuster** [comment]
Sounds good!
