### ISSUE TITLE
reV generation failing for some but not all chunks when run on Himawari v7 data

### ISSUE THREAD

**Issue by EvanRosenlieb** [NREL/reV#378]
**Bug Description**
When running reV Gen for a subset of Himawari v7 points, chunks 02 and 03 for all years always return mean_cf of 0 for all points. All other chunks return valid values. This results in a strip of longitudes for which there are 0 CF's:

<img width="1148" alt="Screen Shot 2022-08-10 at 5 13 52 PM" src="https://user-images.githubusercontent.com/28634124/184215017-395081f4-6e40-458c-8f02-400d55d323cd.png">

These chunks are returning an error in stdout:

**Full Traceback**
Full traceback is in stdout of failed chunk, example here: 

[error.txt](https://github.com/NREL/reV/files/9311272/error.txt)

**To Reproduce**
Steps to reproduce the problem behavior
Run reV gen using the config_gen.json in this directory: /shared-projects/rev/projects/seasia_fpv/

Also uploading here (as text files):

[config_gen.txt](https://github.com/NREL/reV/files/9311281/config_gen.txt)

[samconfig_pv_fixtilt_south.txt](https://github.com/NREL/reV/files/9311303/samconfig_pv_fixtilt_south.txt)
[samconfig_pv_fixtilt_north.txt](https://github.com/NREL/reV/files/9311304/samconfig_pv_fixtilt_north.txt)

**Expected behavior**
ReV gen to complete for all chunks without error

**System (please complete the following information):**
Eagle, using shared reV env.

**Additional context**
Have not been able to find anything odd in the meta data for these points, or in the timeseries resource values for these points (at the very least, spot checking some points within these chunks doesn't show odd values for dni, dhi, windspeed, air temperature)

**Charge code**
WFED.11556.03.02.01

**Comment by grantbuster** [comment]
The weird himawari meta data with [brackets] in country names was being interpreted as a list input and failed when getting passed into json decode. Added a hot fix here: https://github.com/NREL/reV/commit/13525b8802e526dca09cd8ee66784a9f3e01eb60
