### ISSUE TITLE
Add units to applicable supply curve columns

### ISSUE THREAD

**Issue by mmowers** [NREL/reV#379]
**Why this feature is necessary:**
This feature is necessary to be sure of what the column values represent in the _supply-curve.csv files. Some columns already have units (e.g. dist_km, area_sq_km), but others do not (e.g. capacity, elevation, capital_cost, fixed_operating_cost).

**A possible solution is:**
When a column value has units, indicate the unit in the column header.

**I have considered the following alternatives:**
- Documentation that calls out the units for each column. However, relevant documentation can be difficult to find, and this approach would suffer from inconsistency between older versions of the supply curve files and the current documentation (if units are changed over time).

**Additional context**

**Charge code**
If you are at NREL, please provide a task number for the developers to implement this feature.

**Urgency / Timeframe**
This request originates from Trieu Mai, so he (+ Anthony Lopez) would be the best resources for urgency/timeframe.

**Comment by ppinchuk** [comment]
Added in reV 0.9.0+
