### ISSUE TITLE
Python 3.7 not available for M1 Macs 

### ISSUE THREAD

**Issue by cameronbracken** [NREL/reV#380]
**Bug Description**
Anaconda only provides builds of Python 3.8 and higher for M1 Macs, so the command `conda create --name rev python=3.7` is failing. The workaround is to use the Intel build of anaconda but that is not ideal. 

**Full Traceback**
```
> conda create --name rev python=3.7
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - python=3.7

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch
```

```
> conda search python 
Loading channels: done
# Name                       Version           Build  Channel             
python                        3.8.11      hbdb9e5c_5  pkgs/main           
python                        3.8.13      hbdb9e5c_0  pkgs/main           
python                         3.9.6      hc70090a_5  pkgs/main           
python                         3.9.7      hc70090a_1  pkgs/main           
python                        3.9.11      hbdb9e5c_1  pkgs/main           
python                        3.9.11      hbdb9e5c_2  pkgs/main           
python                        3.9.12      hbdb9e5c_0  pkgs/main           
python                        3.9.12      hbdb9e5c_1  pkgs/main           
python                        3.10.0      hbdb9e5c_1  pkgs/main           
python                        3.10.0      hbdb9e5c_2  pkgs/main           
python                        3.10.0      hbdb9e5c_3  pkgs/main           
python                        3.10.0      hbdb9e5c_5  pkgs/main           
python                        3.10.3      hbdb9e5c_5  pkgs/main           
python                        3.10.4      hbdb9e5c_0  pkgs/main 
```

**Code Sample**

```bash
conda create --name rev python=3.7
```

**Expected behavior**
I'd like to be able to install and run reV locally using the native arm64 build of anaconda instead of using the intel build through rosetta. 

**System:**
 - macOC Monterey
 - M1 Pro

**Comment by grantbuster** [comment]
reV is built on PySAM which does not support the m1 architecture. I am not aware of any plans to add m1 support for SAM. 

Also, you should know that reV supports python 3.7 through 3.9, so there's no reason you can't create a 3.9 reV environment on your m1, but then you'll just run into the pysam issue.

**Comment by cameronbracken** [comment]
Good to know. I did try to create 3.8 and 3.8 environments and I did run into the issue installing PySam. I'll stick to the Intel binaries for now.

**Comment by grantbuster** [comment]
Thanks and sorry about that! I also recently got an M1 and was bummed that i couldnt get an optimized reV env set up. Maybe someday but unfortunately i dont think its a research priority for us.
