### ISSUE TITLE
How to retrieve technical potential for a country or region?

### ISSUE THREAD

**Issue by adamsuski** [NREL/reV#382]
Dear NREL colleagues, 

Thank you very much for making these tools open source.
I would like to use NREL’s reV model to calculate the technical potential for wind and solar resources for particular countries, regions, or areas. Unfortunately, I cannot find the appropriate method or option within the tool to do so. My goal is to obtain data similar to the one provided in [this NREL report](https://www.nrel.gov/docs/fy21osti/80892.pdf) in Figure 2: 
<img src=https://user-images.githubusercontent.com/41629710/189339852-b82ab548-8048-4b3d-a9a0-5d382e95132d.png width=50% height=50%>

I will be grateful for any hints or advice. 

Thank you for your time. 

Adam

**Comment by grantbuster** [comment]
@adamsuski, take a look at the reV examples (link below). The main thing you need to do is identify wind/solar resource data that you want to analyze, and then develop a project points input that includes the gid's (meta data indices) that correspond to your region of interest. 

https://github.com/NREL/reV/tree/main/examples/full_pipeline_execution

**Comment by grantbuster** [comment]
Closing this as provided guidance without response

**Comment by jahanbani** [comment]
I'd like to follow up on the above regarding the capabilities of reV. I have a dataset consisting of latitude and longitude coordinates (within the CONUS). My goal is to assess the development potential of each point for wind and solar projects, considering various factors such as terrain, regulatory constraints, land availability, and other restrictions.
Can reV perform this task while considering these constraints? I can provide annual wind/solar generation for each point, however,  I would like to know the available potential for wind/solar in the area of each point given the regulatory and terrain constraints.
