### ISSUE TITLE
Incorporate non-90m Land Use Grids into Minimum Area Filter

### ISSUE THREAD

**Issue by WilliamsTravis** [NREL/reV#384]
**Why this feature is necessary:**
The minimum area filter does not appear to work properly for land use grids that have a resolution other than 90m. 

**A possible solution is:**
When the _area_filter is method is called in exclusions.py [here](https://github.com/NREL/reV/blob/5e834d234949db568560e66f6f7014dfdb9b8cb4/reV/supply_curve/exclusions.py#L940), pass the area in sq km of a single land use cell as an argument ("excl_area"), which is set as a default of .0081 (assuming a 90m grid) in the same script [here](https://github.com/NREL/reV/blob/5e834d234949db568560e66f6f7014dfdb9b8cb4/reV/supply_curve/exclusions.py#L732).

**I have considered the following alternatives:**
I can just apply the minimum area filter to the supply curves in a post-processing step, but I will be missing the "contiguous" part of this function.

**Additional context**
We've been running reV for much smaller study areas lately in which a finer resolution is more computationally feasibly, so we're attempting to improve our capacity estimates by using 10m grids.

**Charge code**
Depending on how much time this will take I may have to confer with the team.

**Urgency / Timeframe**
Not urgent, I can filter these points out manually for a rough estimate.

**Comment by grantbuster** [comment]
10m??? who are we trying to impress?? 

Can you try this dev branch out and see if that works: https://github.com/NREL/reV/tree/gb/min_area_pixel_area

It will just take the area from the exclusion file attributes. 

If this works, do you need a version release?

**Comment by WilliamsTravis** [comment]
Puerto Rico!

Okay sure, will do soon. Don't need version release.

**Comment by grantbuster** [comment]
#385

**Comment by grantbuster** [comment]
closed in #385
