### ISSUE TITLE
Check lat/lon range for PVWatts

### ISSUE THREAD

**Issue by grantbuster** [NREL/reV#387]
**Why this feature is necessary:**
Based on #383, sounds like PVWatts doesn't throw a clear error if lat/lon is out of -90/90 -180/180 range. We should check this in SAM/generation.pvwatts when setting resource. 

**Charge code**
No charge code, easy fix if we have time in any NREL projects. 

**Urgency / Timeframe**
Not urgent. Only affects weird resource data.

**Comment by ppinchuk** [comment]
Added in #415
