### ISSUE TITLE
 List of output variables requested from SAM - Gen.reV_run('windpower', ..., output_request=('gen_profile'))

### ISSUE THREAD

**Issue by Zoe-Fehlau-ES** [NREL/reV#411]
Can a list of the available output variables requested from SAM and information for each one such as units and a description be included in the reV_run documentation? I am trying to determine all the options available and the units attached. Running the below code the best I can find about what values gen.out['gen_profile'] is here on [reV.SAM.generation.WindPower.gen_profile()](https://nrel.github.io/reV/_autosummary/reV.SAM.generation.WindPower.html#reV.SAM.generation.WindPower.gen_profile). And that doesn't explain units if I put output_request=('windspeed'). Anyone know of a list? I have looked in the documentation for output_request and output variables requested from SAM.

gen = Gen.reV_run('windpower', pp, sam_file, res_file, max_workers=1, out_fpath=None, output_request=('gen_profile'))

**Comment by grantbuster** [comment]
Hi Zoe, there's a couple of custom output variables that we implement that can be found in the reV [output attributes files](https://github.com/NREL/reV/blob/main/reV/generation/output_attributes/generation.json) but generally you should be able to request anything from the [PySAM outputs group](https://nrel-pysam.readthedocs.io/en/main/modules/Windpower.html#outputs-group)

**Comment by Zoe-Fehlau-ES** [comment]
Thank you @grantbuster! That is helpful. I must have just not been searching for the correct phrase to find [PySAM outputs group](https://nrel-pysam.readthedocs.io/en/main/modules/Windpower.html#outputs-group). However, I do have a follow-up question then. 
Is there an easy way to change the hub height and system_capacity when running Gen.reV_run for 'windpower' with output_request=('wind_speed')? Or 'temperature'? Or do I have to go into the sam_file (in this case wind_gen_standard_losses_0.json) and change the "system_capacity" and "wind_turbine_hub_ht"?

**Comment by grantbuster** [comment]
We could definitely make the docs a lot better... We're actually working on a large-scale refactor with this in mind right now. 

Yes, the hub height and system capacity are technology parameters that need to be modified in the SAM json and cannot be input as a reV parameter. The one exception is if you're running a lot of different sites with different hub heights and capacities at each site. You can then use the "site_data" input which will modify select key-value pairs in the SAM json for each site.

**Comment by Zoe-Fehlau-ES** [comment]
Is there an example that has different hub heights and capacities at each site that uses the "site_data" input?

**Comment by grantbuster** [comment]
You can see an example in our automated test suite. This isn't run from cli, instead run directly from the python entry point, but you get the idea:

https://github.com/NREL/reV/blob/main/tests/test_gen_wind.py#L253-L274
