### ISSUE TITLE
Solar Run - Rev issue with ghi_means

### ISSUE THREAD

**Issue by smthomson37** [NREL/reV#419]
**Bug Description**
When running reV for solar (clearsky, may occur with non-clearsky) the ghi means are causing the run to fail.

**Full Traceback**
reV.utilities.exceptions.SAMExecutionError: Could not retrieve outputs "['ghi_means']" from PySAM object "<Pvwattsv8 object at 0x2ba08c75ec60>".
**Code Sample**
A copy-pastable example if possible

```python
{
    "log_directory": "./logs",
    "execution_control": {
        "allocation": "rev",
        "feature": "--qos=normal",
        "memory_utilization_limit": 0.6,
        "memory": 90,
        "nodes": 1,
        "option": "eagle",
        "sites_per_worker": 100,
        "walltime": 1.0,
        "feature": "-p debug"
    },
    "log_level": "DEBUG",
    "analysis_years": [
        2012
],
    "technology": "pvwattsv8",
    "output_request": [
        "cf_profile",
        "cf_mean",
        "ghi_mean",
        "lcoe_fcr",
    	"ac",
    	"dc",
        "clipped_power"
    ],
    "project_points": "./solar_project_points.csv",
    "sam_files": {
        "default": "./sam_config.json"
    },
    "resource_file": "/datasets/NSRDB/current/nsrdb_{}.h5"
}

```

**To Reproduce**
Steps to reproduce the problem behavior
1. Go to /shared-projects/rev/projects/abb/rev/upv/clearsky/
2. run rrlogs -o 0 to see the error

**Expected behavior**
successful revrun

**Screenshots**

**System (please complete the following information):**
 - running on eagle debug node

**Additional context**

**Charge code**
If you are at NREL and fixing this bug is urgent, please provide a charge code for our time.

**Comment by grantbuster** [comment]
The exception says "ghi_means" but the config says "ghi_mean"... are both correct?

**Comment by smthomson37** [comment]
Ran the config gen with :
ghi_means
auto corrects to:
Subprocess received stderr: 
`Subprocess received stderr: 
/vast/shared-projects/rev/modulefiles/alternate_repos/reV/reV/config/output_request.py:45: ConfigWarning: Correcting output request "ghi_means" to "ghi_mean".
  warn(msg, ConfigWarning)`

**Comment by smthomson37** [comment]
Closing this as I believe it was user error causing this issue.
