### ISSUE TITLE
Add ability to use "actuals" project points to run ECMWF forecasts through reV gen

### ISSUE THREAD

**Issue by MRossol** [NREL/reV#43]

**Comment by grantbuster** [comment]
okay so for reV running multiple technologies off of a single resource gid, what we should do is have an input kwarg that is "forecast_gid_map" so we can input resource gids in the project points and dynamically map those to forecast gids (the "real" gids of the resource input file). reV project points will always use the full-resolution resource gids and then the rex Resource preload_sam() class method will intercept the full-resolution resource gids and map the low-res resource appropriately.

This has a few inherent benefits: 
1. we wont be messing with duplicate resource gids in reV (there is a lot of code that uses this as a fundamental assumption)
2. if you wanted to run the full-resolution resource with multiple technologies at a location you could hack it by using the gid mapping while maintaining all of the downstream reV functionality.

**Comment by MRossol** [comment]
implemented in #303
