### ISSUE TITLE
Calculating of Technical Potential for a List of Geographic Points

### ISSUE THREAD

**Issue by jahanbani** [NREL/reV#430]
I have a dataset of latitude and longitude coordinates (within the CONUS). My goal is to assess the development potential of each point for wind and solar projects, considering various factors such as terrain, regulatory constraints, land availability, and other restrictions.
Can reV perform this task while considering these constraints? I can provide annual wind/solar generation for each point. However, I would like to know the available potential for wind/solar in the area of each point, given the regulatory and terrain constraints.

**Comment by ppinchuk** [comment]
Hi @jahanbani. Yes, reV can help you do that, but you will need to provide the geospatial data yourself. If you have that data around and are ready to run the model, please see the [CLI Documentation](https://nrel.github.io/reV/_cli/reV.html).

If you are new to reV, I suggest you reference the [original reV technical report](https://www.nrel.gov/docs/fy19osti/73067.pdf) as well as our [updated wind modeling methodology](https://www.nrel.gov/docs/fy24osti/85075.pdf) to familiarize yourself with reV functionality. 

If you do not have geospatial data you can provide for the model, perhaps you can use our [annual standard scenarios modeling results](https://www.nrel.gov/gis/renewable-energy-supply-curves.html) instead.

**Comment by jahanbani** [comment]
Thank you, @ppinchuk, 

Just to confirm, when you say "geospatial data", are you referring to the exclusion file that contains information on regulatory and geographic restrictions for developing wind or solar energy in each location? If that's the case, unfortunately, I don't have access to that data. However, I was wondering if you know whether such data is available through NREL.

Regarding transmission line costs, do I also need geospatial data for that? If so, is there any data available on NREL similar to the supply curves that you provided the link to?

Thank you for your assistance, it's greatly appreciated.

**Comment by ppinchuk** [comment]
@jahanbani yes, reV uses high-resolution geospatial layers of terrain topology, zoning setbacks, and other exclusions as input to determine the geographic restrictions at each location. As of right now, that data is not available through NREL, though we are working towards making it publicly accessible. No timeline on that yet, but at some point in the future you will be able to get access to at least some of that data.

Transmission line costs are also geospatial in nature. We have a tool in our [sister repository, reVX](https://github.com/NREL/reVX/tree/main/reVX/least_cost_xmission#least-cost-transmission-paths), that helps you calculate the transmission costs as required by reV. However, this tool still needs a high-resolution input of terrain (among other things), so you may have to wait until that data becomes available to run this as well. That being said, the supply curves in the link I provided have associated transmission costs given for each point. They also give the total land available at each point after exclusions, so perhaps there is a way you can leverage that data for your analysis.

**Comment by ppinchuk** [comment]
@jahanbani Do you have any other questions? Otherwise I will mark this issue as resolved

**Comment by jahanbani** [comment]
@ppinchuk Thank you for the information. Very helpful.
I have a few questions about the transmission line costs.
1. What voltage level has been assumed for the transmission line connection? 
2. What is the voltage level of the closest substation that the transmission cost is given for?
3. Does "reinforcement_cost_per_mw" contain the "reg_mult"?
Thank you very much.

**Comment by ppinchuk** [comment]
No problem.

1) We model several voltage lines, each with their own capacity. Currently, we allow 69kV, 138kV, and 230kV lines. Each line can be used to connect to a farm (supply curve point), but only if the capacity of the line is large enough to accommodate the reV output capacity for that location. If more than one line fit this criteria, the cheapest one is chosen.
2) Substation voltages can also vary, but we require all substations to have a minimum of 69kV in order to be included in the modeling.
3) No, none of the transmission costs include the `reg_mult`. This value is used exclusively for the calculation of `mean_lcoe` (i.e. the plant LCOE based on resource alone)

**Comment by ppinchuk** [comment]
Any other questions @jahanbani?
