### ISSUE TITLE
generation module keywords error

### ISSUE THREAD

**Issue by isatkaus** [NREL/reV#431]
**Bug Description**
when running rev=0.8.2 generation module with execution keyword "qos": "normal" (as described in current docs) jobs do not get kicked off (on Kestrel). but if instead using "feature":"--qos=normal" (as I was doing for versions before 0.8.2 ) everything works fine. so either there is a mistake in the docs, or a bug in the code

**Full Traceback**
(buildouts)[isatkaus@x1008c0s4b1n0 wind-gen-tamu200-v6]$ reV generation -c config_gen.json
gaps (INFO) - [config.py:233] : Running generation from config file: '/kfs2/projects/hpcapps/isatkaus/grid-buildouts-data/rev-runs/wind-gen-tamu200-v6/config_gen.json'
gaps (INFO) - [config.py:238] : Target output directory: '/kfs2/projects/hpcapps/isatkaus/grid-buildouts-data/rev-runs/wind-gen-tamu200-v6'
gaps (INFO) - [config.py:239] : Target logging directory: '/kfs2/projects/hpcapps/isatkaus/grid-buildouts-data/rev-runs/wind-gen-tamu200-v6/logs'
INFO - 2023-11-02 10:09:40,568 [cli_functions.py:31] : Initialized reV/rex loggers with name 'wind-gen-tamu200-v6_generation' and log directory '/kfs2/projects/hpcapps/isatkaus/grid-buildouts-data/rev-runs/wind-gen-tamu200-v6/logs'
INFO - 2023-11-02 10:09:40,568 [cli_gen.py:96] : The following project points were specified: "pp.csv"
INFO - 2023-11-02 10:09:40,568 [cli_gen.py:98] : The following SAM configs are available to this run:
{   'default': '/home/isatkaus/projects/hpcapps/grid-buildouts-data/rev-runs/wind-gen-tamu200-v6/wind_gen_2atb_turbine.json'}
INFO - 2023-11-02 10:09:40,568 [cli_gen.py:101] : The following is being used for site specific input data: "None"
Traceback (most recent call last):
  File "/projects/hpcapps/isatkaus/conda-envs/buildouts/bin/reV", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/kfs2/projects/hpcapps/isatkaus/conda-envs/buildouts/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/kfs2/projects/hpcapps/isatkaus/conda-envs/buildouts/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/kfs2/projects/hpcapps/isatkaus/conda-envs/buildouts/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/kfs2/projects/hpcapps/isatkaus/conda-envs/buildouts/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/kfs2/projects/hpcapps/isatkaus/conda-envs/buildouts/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/kfs2/projects/hpcapps/isatkaus/conda-envs/buildouts/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/kfs2/projects/hpcapps/isatkaus/conda-envs/buildouts/lib/python3.11/site-packages/gaps/cli/config.py", line 391, in from_config
    _FromConfig(ctx, config_file, command_config).run()
  File "/kfs2/projects/hpcapps/isatkaus/conda-envs/buildouts/lib/python3.11/site-packages/gaps/cli/config.py", line 382, in run
    .kickoff_jobs()
     ^^^^^^^^^^^^^^
  File "/kfs2/projects/hpcapps/isatkaus/conda-envs/buildouts/lib/python3.11/site-packages/gaps/cli/config.py", line 289, in kickoff_jobs
    kickoff_job(self.ctx, cmd, deepcopy(self.exec_kwargs))
  File "/kfs2/projects/hpcapps/isatkaus/conda-envs/buildouts/lib/python3.11/site-packages/gaps/cli/execution.py", line 66, in kickoff_job
    _kickoff_hpc_job(ctx, cmd, hardware_option, **exec_kwargs)
  File "/kfs2/projects/hpcapps/isatkaus/conda-envs/buildouts/lib/python3.11/site-packages/gaps/cli/execution.py", line 152, in _kickoff_hpc_job
    out = ctx.obj["MANAGER"].submit(name, cmd=cmd, **kwargs)[0]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/kfs2/projects/hpcapps/isatkaus/conda-envs/buildouts/lib/python3.11/site-packages/gaps/hpc.py", line 215, in submit
    out, err = submit(
               ^^^^^^^
  File "/kfs2/projects/hpcapps/isatkaus/conda-envs/buildouts/lib/python3.11/site-packages/gaps/hpc.py", line 661, in submit
    stdout, stderr = _subprocess_popen(cmd)
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/kfs2/projects/hpcapps/isatkaus/conda-envs/buildouts/lib/python3.11/site-packages/gaps/hpc.py", line 603, in _subprocess_popen
    raise OSError(
OSError: Subprocess submission failed with return code 1 and stderr:
sbatch: error: Valid settings for QoS with -q is standby, normal, or high.
sbatch: error: Batch job submission failed: Invalid qos specification
(buildouts)[isatkaus@x1008c0s4b1n0 wind-gen-tamu200-v6]$ 

**Code Sample** config_gen.json
{
  "analysis_years": [
    2007
  ],
  "execution_control": {
    "allocation": "exasgd",
    "memory": 90,
    "nodes": 20,
    "option": "kestrel",
    "qos": "normal",
    "sites_per_worker": 100,
    "walltime": 4.0
  },
  "log_directory": "./logs/",
  "log_level": "INFO",
  "output_request": [
    "cf_mean",
    "cf_profile",
    "gen_profile",
    "lcoe_fcr",
    "ws_mean",
    "annual_energy"
  ],
  "project_points": "pp.csv",
  "resource_file": [
    "/kfs2/pdatasets/WIND/conus/v1.0.0/2008/wtk_conus_2007_*.h5"
  ],
  "sam_files": {
    "default": "/home/isatkaus/projects/hpcapps/grid-buildouts-data/rev-runs/wind-gen-tamu200-v6/wind_gen_2atb_turbine.json"
  },
  "technology": "windpower"
}

```python
# Your code here

```

**To Reproduce**
Steps to reproduce the problem behavior
run rev=0.8.2 with execution control as in above .json on Kestrel

**Expected behavior**
will fail to kick off the jobs

**Screenshots**

**System (please complete the following information):**
Kestrel, rev=0.8.2

**Additional context**

**Charge code**
no rush, since it works fine with old use of "feature":"--qos=normal". however, it took me entire day to figure this bug out, so I think it would be helpful if docs were fixed, so that other users won't have to waste their time.

**Comment by isatkaus** [comment]
OK. my gaps version is 0.6.1.
I just installed reV a couple of days ago (pip install nrel-rev) – how would reinstalling it help?

Thank you,
Ignas.

From: Paul Pinchuk ***@***.***>
Date: Thursday, November 2, 2023 at 10:40 AM
To: NREL/reV ***@***.***>
Cc: Satkauskas, Ignas ***@***.***>, Mention ***@***.***>
Subject: Re: [NREL/reV] generation module keywords error (Issue #431)

CAUTION: This email originated from outside of NREL. Do not click links or open attachments unless you recognize the sender and know the content is safe.

Hi @isatkaus<https://github.com/isatkaus>, how recently did you install reV? I don't know for sure, but it looks like your GAPs version may be out of date.
Can you run this in your reV env? python -c "import gaps; print(gaps.__version__)"
If it outputs anything less than 0.6.2, please re-install reV

**Comment by ppinchuk** [comment]
Oops, 0.6.1 is the most recent GAPs version, so that should be ok. 
Reinstalling reV would update your packages, in case any are out of date. Looks like that is not the culprit in this case.

I just tried your sample config and the job kicked off just fine for me on kestrel. I didn't complete - looks like your resource file path does not exist on that machine (mixup between 2007 and 2008)?

The reV documentation is up-to-date. The  `qos` keyword in the execution control is what *should* be used.
If you encountered a case where the `qos` keyword doesn't work, that would be a bug that needs to be fixed.
 
Since I cannot reproduce the problem, it will be difficult for me to push any fix. Do you by chance still have the complete logs from the failed run?

**Comment by isatkaus** [comment]
I’ve tried like 3 different allocations (they all have AU’s on Kestrel), got same error.
Year mix-up is not the problem – I fixed it and got the same error.
The only logs I get is in “wind-gen-tamu200-v6_generation.log” (stdout dir is empty).

gaps (INFO) - [config.py:233] : Running generation from config file: '/kfs2/projects/hpcapps/isatkaus/grid-buildouts-data/rev-runs/wind-gen-tamu200-v6/config_gen.json'
gaps (INFO) - [config.py:238] : Target output directory: '/kfs2/projects/hpcapps/isatkaus/grid-buildouts-data/rev-runs/wind-gen-tamu200-v6'
gaps (INFO) - [config.py:239] : Target logging directory: '/kfs2/projects/hpcapps/isatkaus/grid-buildouts-data/rev-runs/wind-gen-tamu200-v6/logs'
INFO - 2023-11-02 11:06:08,437 [cli_functions.py:31] : Initialized reV/rex loggers with name 'wind-gen-tamu200-v6_generation' and log directory '/kfs2/projects/hpcapps/isatkaus/grid-buildouts-data/rev-runs/wind-gen-tamu200-v6/logs'
INFO - 2023-11-02 11:06:08,437 [cli_gen.py:96] : The following project points were specified: "pp.csv"
INFO - 2023-11-02 11:06:08,437 [cli_gen.py:98] : The following SAM configs are available to this run:
{   'default': '/home/isatkaus/projects/hpcapps/grid-buildouts-data/rev-runs/wind-gen-tamu200-v6/wind_gen_2atb_turbine.json'}
INFO - 2023-11-02 11:06:08,437 [cli_gen.py:101] : The following is being used for site specific input data: "None"


The problem I do not get is why does it work totally fine if I do “feature”:”—qos=normal”? should it not work in rev=0.8.2?

Also, I am running reV generation command from shared partition of Kestrel (not sure if that matters at all).

I’ve reinstalled and installed reV:
pip install "nrel-rev==0.7.0"
pip install "nrel-rev==0.8.2"

Btw, I’m running with python 3.11 (I’ve had problems with pysam because of that).

Oh, and one more thing, I get somewhat similar but different error if I use “qos”:”standby” (below)

***@***.*** wind-gen-tamu200-v6]$ reV generation -c config_gen.json
gaps (INFO) - [config.py:233] : Running generation from config file: '/kfs2/projects/hpcapps/isatkaus/grid-buildouts-data/rev-runs/wind-gen-tamu200-v6/config_gen.json'
gaps (INFO) - [config.py:238] : Target output directory: '/kfs2/projects/hpcapps/isatkaus/grid-buildouts-data/rev-runs/wind-gen-tamu200-v6'
gaps (INFO) - [config.py:239] : Target logging directory: '/kfs2/projects/hpcapps/isatkaus/grid-buildouts-data/rev-runs/wind-gen-tamu200-v6/logs'
INFO - 2023-11-02 11:22:20,601 [cli_functions.py:31] : Initialized reV/rex loggers with name 'wind-gen-tamu200-v6_generation' and log directory '/kfs2/projects/hpcapps/isatkaus/grid-buildouts-data/rev-runs/wind-gen-tamu200-v6/logs'
INFO - 2023-11-02 11:22:20,601 [cli_gen.py:96] : The following project points were specified: "pp.csv"
INFO - 2023-11-02 11:22:20,602 [cli_gen.py:98] : The following SAM configs are available to this run:
{   'default': '/home/isatkaus/projects/hpcapps/grid-buildouts-data/rev-runs/wind-gen-tamu200-v6/wind_gen_2atb_turbine.json'}
INFO - 2023-11-02 11:22:20,602 [cli_gen.py:101] : The following is being used for site specific input data: "None"
gaps (ERROR) - [execution.py:106] : Requested Quality-of-service option ('standby') not recognized! Available options are: {'unspecified', 'normal', 'high'}.
Traceback (most recent call last):
  File "/kfs2/projects/hpcapps/isatkaus/conda-envs/buildouts/lib/python3.11/site-packages/gaps/cli/execution.py", line 99, in _filter_exec_kwargs
    qos = QOSOption(qos)
          ^^^^^^^^^^^^^^
  File "/kfs2/projects/hpcapps/isatkaus/conda-envs/buildouts/lib/python3.11/enum.py", line 695, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/kfs2/projects/hpcapps/isatkaus/conda-envs/buildouts/lib/python3.11/enum.py", line 1111, in __new__
    raise ve_exc
ValueError: 'standby' is not a valid QOSOption

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/projects/hpcapps/isatkaus/conda-envs/buildouts/bin/reV", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/kfs2/projects/hpcapps/isatkaus/conda-envs/buildouts/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/kfs2/projects/hpcapps/isatkaus/conda-envs/buildouts/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/kfs2/projects/hpcapps/isatkaus/conda-envs/buildouts/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/kfs2/projects/hpcapps/isatkaus/conda-envs/buildouts/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/kfs2/projects/hpcapps/isatkaus/conda-envs/buildouts/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/kfs2/projects/hpcapps/isatkaus/conda-envs/buildouts/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/kfs2/projects/hpcapps/isatkaus/conda-envs/buildouts/lib/python3.11/site-packages/gaps/cli/config.py", line 391, in from_config
    _FromConfig(ctx, config_file, command_config).run()
  File "/kfs2/projects/hpcapps/isatkaus/conda-envs/buildouts/lib/python3.11/site-packages/gaps/cli/config.py", line 382, in run
    .kickoff_jobs()
     ^^^^^^^^^^^^^^
  File "/kfs2/projects/hpcapps/isatkaus/conda-envs/buildouts/lib/python3.11/site-packages/gaps/cli/config.py", line 289, in kickoff_jobs
    kickoff_job(self.ctx, cmd, deepcopy(self.exec_kwargs))
  File "/kfs2/projects/hpcapps/isatkaus/conda-envs/buildouts/lib/python3.11/site-packages/gaps/cli/execution.py", line 63, in kickoff_job
    exec_kwargs = _filter_exec_kwargs(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/kfs2/projects/hpcapps/isatkaus/conda-envs/buildouts/lib/python3.11/site-packages/gaps/cli/execution.py", line 106, in _filter_exec_kwargs
    raise gapsConfigError(msg) from err
gaps.exceptions.gapsConfigError: Requested Quality-of-service option ('standby') not recognized! Available options are: {'unspecified', 'normal', 'high'}.
***@***.*** wind-gen-tamu200-v6]$





From: Paul Pinchuk ***@***.***>
Date: Thursday, November 2, 2023 at 11:03 AM
To: NREL/reV ***@***.***>
Cc: Satkauskas, Ignas ***@***.***>, Mention ***@***.***>
Subject: Re: [NREL/reV] generation module keywords error (Issue #431)

CAUTION: This email originated from outside of NREL. Do not click links or open attachments unless you recognize the sender and know the content is safe.

Oh, I just remembered that I have seen this before. This is not a reV issue. I believe your allocation is out of AU's.
Please try the run with a different allocation that definitely has AU hours left over.

**Comment by ppinchuk** [comment]
OK, yea, that is strange.
reV is technically only tested thru python 3.10, which is why we may have not seen this error before. In fact, when I tried to update GAPs (one of the underlying frameworks, as mentioned above) to Python 3.11 and 3.12, I ran into a bunch of tests that failed, and haven't gotten around to fixing them yet. These may be related.

`The problem I do not get is why does it work totally fine if I do “feature”:”—qos=normal”` - I don't have an answer for this right now. We can't stop you from specifying qos as a feature flag instead of a keyword argument, so likely the issue is that something is breaking during the parsing of the QOS value when you specify it as a keyword in Python 3.11 and 3.12.

I'll go ahead and work on officially supporting python 3.11 and 3.12 in GAPS and reV, and then we can see if this issue persists.
In the meantime, your temporary fix should suffice

**Comment by isatkaus** [comment]
Yep, it was python=3.11. when I downgraded my conda env to 3.10, it all worked as expected.


From: Paul Pinchuk ***@***.***>
Date: Thursday, November 2, 2023 at 11:48 AM
To: NREL/reV ***@***.***>
Cc: Satkauskas, Ignas ***@***.***>, Mention ***@***.***>
Subject: Re: [NREL/reV] generation module keywords error (Issue #431)

CAUTION: This email originated from outside of NREL. Do not click links or open attachments unless you recognize the sender and know the content is safe.

OK, yea, that is strange.
reV is technically only tested thru python 3.10, which is why we may have not seen this error before. In fact, when I tried to update GAPs (one of the underlying frameworks, as mentioned above) to Python 3.11 and 3.12, I ran into a bunch of tests that failed, and haven't gotten around to fixing them yet. These may be related.

The problem I do not get is why does it work totally fine if I do “feature”:”—qos=normal” - I don't have an answer for this right now. We can't stop you from specifying qos as a feature flag instead of a keyword argument, so likely the issue is that something is breaking during the parsing of the QOS value when you specify it as a keyword in Python 3.11 and 3.12.

I'll go ahead and work on officially supporting python 3.11 and 3.12 in GAPS and reV, and then we can see if this issue persists.
In the meantime, your temporary fix should suffice

**Comment by ppinchuk** [comment]
Yea, looks like Python 3.11 has a braking change to the `Enum` class, which is what the `qos` specifier relies heavily upon.
I've already fixed the issue in GAPs, and am now working on getting reV up on 3.11. Glad to hear everything works as expected on 3.10 though!

**Comment by isatkaus** [comment]
Great, let me know when you get it to work with 3.11.
And thank you for all your help.

From: Paul Pinchuk ***@***.***>
Date: Thursday, November 2, 2023 at 2:03 PM
To: NREL/reV ***@***.***>
Cc: Satkauskas, Ignas ***@***.***>, Mention ***@***.***>
Subject: Re: [NREL/reV] generation module keywords error (Issue #431)

CAUTION: This email originated from outside of NREL. Do not click links or open attachments unless you recognize the sender and know the content is safe.

Yea, looks like Python 3.11 has a braking change to the Enum class, which is what the qos specifier relies heavily upon.
I've already fixed the issue in GAPs, and am now working on getting reV up on 3.11. Glad to hear everything works as expected on 3.10 though!

**Comment by ppinchuk** [comment]
Ok, reV 0.8.3 should now be compatible with Python 3.11. Please give that a try and let me know if you run into any other issues

**Comment by isatkaus** [comment]
Yes, it worked for me now on 3.11. At least I got them to kick off, which was the problem before.
Thank you for your help.


From: Paul Pinchuk ***@***.***>
Date: Thursday, November 2, 2023 at 10:02 PM
To: NREL/reV ***@***.***>
Cc: Satkauskas, Ignas ***@***.***>, Mention ***@***.***>
Subject: Re: [NREL/reV] generation module keywords error (Issue #431)

CAUTION: This email originated from outside of NREL. Do not click links or open attachments unless you recognize the sender and know the content is safe.

Ok, reV 0.8.3 should now be compatible with Python 3.11. Please give that a try and let me know if you run into any other issues
