### ISSUE TITLE
pySAM link appears incorrect?

### ISSUE THREAD

**Issue by jpvelez** [NREL/reV#460]
**Bug Description**

This is not a bug with the software, but possibly with the docs. It looks like there's a few spots where you try to link to a python library for SAM, but it seems to be pointing to an [unrelated genomics library](https://pysam.readthedocs.io/en/latest/) with the same name?

**Comment by ppinchuk** [comment]
Hi, could you please show a specific example?

For instance, [this line](https://nrel.github.io/reV/_autosummary/reV.SAM.generation.WindPower.html#:~:text=See%20the%20PySAM%20Windpower%20documentation%20for%20the%20configuration%20keys%20required%20in%20the) seems to link to PySAM as expected. I spot-checked a few other links as well and they all pointed me to the correct PySAM documentation.

**Comment by jpvelez** [comment]
Sure! [Here's all of them](https://github.com/search?q=repo:NREL/reV%20https://pysam.readthedocs.io/en/latest/&type=code) ;)

**Comment by ppinchuk** [comment]
Thanks! Will get this fixed as soon as I can!

**Comment by jpvelez** [comment]
My pleasure! Keep up the awesome work.
