### ISSUE TITLE
Support passing extracted dict as sam_files input arg into Gen.reV_run and Econ.reV_run instead of JSON path

### ISSUE THREAD

**Issue by MRossol** [NREL/reV#47]
Enable the ability to run Gen and Econ from a dictionary instead of only from a json path

**Comment by grantbuster** [comment]
@MRossol where is this example? Doesnt this issue want a dict input for the SAM config? I'm pretty sure we cant do that right now.

**Comment by MRossol** [comment]
touche, though I'm wondering if thats still needed...

**Comment by grantbuster** [comment]
it is, i know this because kevin mccabe asked me about it today

**Comment by grantbuster** [comment]
pretty sure just a more relaxed constraint here would do it: https://github.com/NREL/reV/blob/ced8d9402807d1aef50eda6851b29cbf9507f989/reV/config/sam_config.py#L170-L180

**Comment by MRossol** [comment]
Task number: WEPG -> 10346 - 43.01.06

**Comment by MRossol** [comment]
Implemented in #286
