### ISSUE TITLE
Regional Capital Cost Multipliers

### ISSUE THREAD

**Issue by alopez04** [NREL/reV#65]
Can you please add the ability to incorporate regional capital cost multipliers? These would be applied pre LCOE calculation. 

Example multipliers below. 
![image](https://user-images.githubusercontent.com/9019826/69258579-0f5ead00-0b7a-11ea-8df4-d57a78abfba5.png)

**Comment by MRossol** [comment]
Can be accomplished using site econ data:
Analysts put together a table mapping sites to capital costs. The cc multipliers could be in the table. 

@alopez04  does the above suffice?
